# Generated by Django 3.0.8 on 2020-09-23 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('user_ip', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
        ),
    ]
